### ISSUE TITLE
SITL: generate HTML file to view exported KML and link charts

### ISSUE THREAD

**Issue by AndreasAntener** [PX4/containers#17]
Related to #10

**Comment by dagar** [comment]
https://github.com/PX4/Firmware/issues/5954

**Comment by dagar** [comment]
Would uploading each build to http://logs.px4.io/ be sufficient?

**Comment by LorenzMeier** [comment]
Yes, if you post the link via Jenkins then.

**Comment by AndreasAntener** [comment]
Replaced by Flight Review upload
