### ISSUE TITLE
Gazebo fails to run on bionic (18.04) while using nvidia drivers

### ISSUE THREAD

**Issue by tprasadtp** [PX4/containers#174]
This issue is caused by two problems. 

**I have tested it only with `px4io/px4-dev-ros:latest`**

Issue:
1. Nvidia drivers not installed in the container
2. Nvidia version on host and in container should match **exactly**. 

Cause:
1. Nvidia drivers should be installed inside the container, failing to do so would result in errors like this

```console
root@78f1b36c0806:/# gazebo --verbose
Gazebo multi-robot simulator, version 7.14.0
Copyright (C) 2012 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

[Msg] Waiting for master.
Gazebo multi-robot simulator, version 7.14.0
Copyright (C) 2012 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

[Msg] Waiting for master.
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 172.17.0.2
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
[Err] [RenderEngine.cc:749] Unable to create glx visual
[Wrn] [RenderEngine.cc:97] Unable to create X window. Rendering will be disabled
[Wrn] [RenderEngine.cc:301] Cannot initialize render engine since render path type is NONE. Ignore this warning ifrendering has been turned off on purpose.
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 172.17.0.2
[Wrn] [GuiIface.cc:256] Couldn't locate specified .ini. Creating file at "/home/user/.gazebo/gui.ini"
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
[Err] [RenderEngine.cc:749] Unable to create glx visual
[Wrn] [RenderEngine.cc:97] Unable to create X window. Rendering will be disabled
[Wrn] [RenderEngine.cc:301] Cannot initialize render engine since render path type is NONE. Ignore this warning ifrendering has been turned off on purpose.
[Err] [GLWidget.cc:179] GLWidget could not create a scene. This will likely result in a blank screen.
[Err] [ModelEditor.cc:75] User camera is NULL. Non-editable models will keep their original material
```

2. Even after installing the driver, Because  Version of docker image on docker hub is still based on xenial. So the driver version are different in host and container it will still error out something like this

```console
root@78f1b36c0806:/# gazebo --verbose
Gazebo multi-robot simulator, version 7.14.0
Copyright (C) 2012 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

[Msg] Waiting for master.
Gazebo multi-robot simulator, version 7.14.0
Copyright (C) 2012 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

[Msg] Waiting for master.
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 172.17.0.2
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  154 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  24
  Current serial number in output stream:  25
```

Perhaps include in `README` about this? I am not sure whether creating Dockerfile/image for every nvidia version would be reasonable? But nvidia does provide docker images may be they can be used? 

Edit: #172 might help in this regard. But it still would require matching nvidia drivers on host and container.

**Comment by lamping7** [comment]
`latest` is generally a bad idea. You don't know what you're getting. There were a couple images that didn't have the master branch setup to correspond with `latest` (including the one you're using). If you look at the Dockerfile, you'll see that you're actually supposed to get ROS melodic and Ubuntu 18, but you're not with the `latest` you have. I just configured them in docker hub to sync `latest` with master. It'll take a while for them to be available (probably 1 or 2 hrs). I'm going to close this for now as it doesn't really correlate with the current state of the image you're trying to use. Please re-open if you still have a problem once you sort out the proper tag version.
