### ISSUE TITLE
jmavsim assistive_technologies error

### ISSUE THREAD

**Issue by zwn** [PX4/containers#206]
The image px4io/px4-dev-simulation-bionic c50c4f5eb0af fails to run jmavsim, showing error. The fix from https://github.com/PX4/Firmware/issues/9557#issuecomment-512137607 makes it work.

```
sed -i "s/^assistive_technologies=/#&/" /etc/java-8-openjdk/accessibility.properties
```

Somewhere in the Dockerfile should do it. 

Alternatively it could be fixed in the run script for jmavsim as suggested here: https://askubuntu.com/a/1134254/539354

I have tried both options - both work.

**Comment by julianoes** [comment]
Thanks @zwn for the suggestion. I've created a pull request against Firmware to fix it there.

https://github.com/PX4/Firmware/pull/13908
