### ISSUE TITLE
DockerfileSnapdragon too big for semaphoreci

### ISSUE THREAD

**Issue by dagar** [PX4/containers#38]
The snappy build on semaphoreci was failing due to the size of the docker image. Unfortunately semaphoreci doesn't keep build history for deleted branches.

It's been deleted from the PX4 semaphore configuration for now.

    docker-cache restore
    docker pull julianoes/px4-snappy-2016-10-16
    docker run --rm -v `pwd`:`pwd`:rw -v $SEMAPHORE_CACHE_DIR/ccache:$HOME/.ccache:rw -e CCACHE_DIR=$HOME/.ccache -e CCACHE_SLOPPINESS=time_macros -w=`pwd` --user=root -it julianoes/px4-snappy-2016-10-16 /bin/bash -c "make eagle_default"

FYI @julianoes @mcharleb

**Comment by julianoes** [comment]
I was trying to create a smaller docker image but I'm currently blocked by https://github.com/ATLFlight/cross_toolchain/pull/10.

**Comment by mcharleb** [comment]
@julianoes Merged, sorry didn't see the PR.

**Comment by mcharleb** [comment]
@julianoes @dagar Let me know what I can do to make this work. @julianoes do you need a script to reduce the hexagon SDK to a bare minimum?

**Comment by dagar** [comment]
Ping me when it's time to re-enable semaphore.

**Comment by julianoes** [comment]
@mcharleb the problem is that the cmake gcc check suddenly uses target/hexagon/lib/v60 instead of v50, so the `-trim` option for `installv3.sh` can't be applied anymore, thus leading to a bigger image.

**Comment by mcharleb** [comment]
@julianoes I can fix the cmake gcc check.

**Comment by mcharleb** [comment]
@julianoes I updated installv3.sh and removed more files with the -trim option. It seems to work for me. Let me know if you have any issues

**Comment by mcharleb** [comment]
@julianoes You will also need an updated cmake_hexagon: https://github.com/ATLFlight/cmake_hexagon/commit/a55fb8e306b06a4d3ab7f46536904b045923f46a

**Comment by dagar** [comment]
docker pull lorenzmeier/px4-dev-snapdragon
    docker run --rm -v `pwd`:`pwd`:rw -e CI=true -w=`pwd` -e LOCAL_USER_ID=$UID -it lorenzmeier/px4-dev-snapdragon /bin/bash -c "make eagle_default"

**Comment by mcharleb** [comment]
@dagar @julianoes @LorenzMeier I created docker images for Snapdragon Flight and buid tests: https://github.com/ATLFlight/containers

You still need access the the Hexagon SDK and qrlSDK to create them.

**Comment by dagar** [comment]
Solved with minimalSDK.tgz
