### ISSUE TITLE
Jenkins Github authentication

### ISSUE THREAD

**Issue by AndreasAntener** [PX4/containers#4]
Integrate Github authentication in Jenkins SITL CI server (for management users)

**Comment by dagar** [comment]
I added this to sitl01.dronetest.io tonight.
Right now anyone in PX4 has full access. We may need to review.

**Comment by jgoppert** [comment]
Awesome, so useful for cancelling wasted builds.

**Comment by dagar** [comment]
@jgoppert can I take that as confirmation it's working for more than just me? I already had a local account.
