### ISSUE TITLE
Protobuf version issues in latest px4-dev-simulation build

### ISSUE THREAD

**Issue by Butakus** [PX4/containers#90]
Hi,

It seems the latest [px4-dev-simulation](https://hub.docker.com/r/px4io/px4-dev-simulation/) image in Docker Hub contains a custom build of protobuf installed in /usr/local. This causes the Firmware (concretely sitl_gazebo) build to fail, since gazebo messages are generated with a different version of protobuf (the one in the ubuntu repository).

This is the output of pulling this image and showing the contents of /usr/local in the container:

```
$ docker run -it px4io/px4-dev-simulation:latest /bin/bash
Unable to find image 'px4io/px4-dev-simulation:latest' locally
latest: Pulling from px4io/px4-dev-simulation
50aff78429b1: Already exists 
f6d82e297bce: Already exists 
275abb2c8a6f: Already exists 
9f15a39356d6: Already exists 
fc0342a94c89: Already exists 
cc216fcc1d2b: Pull complete 
cc9528aeebd2: Pull complete 
c9df7377b2b3: Pull complete 
b0391a942697: Pull complete 
Digest: sha256:75b6da223d372325a336e2f8fcc3b44bcdb51a1216d4b9d2b6a5b72016d4ac12
Status: Downloaded newer image for px4io/px4-dev-simulation:latest
Starting with UID : 9001
user@751f7fa9d4be:/$ ls /usr/local/include/
capstone  gmock  google  gtest  re2
user@751f7fa9d4be:/$ ls /usr/local/include/google/
protobuf
```

If I build the px4-dev-simulation image manually from its Dockerfile everything is fine. Nothing goes to /usr/local and I can build the Firmware and sitl_gazebo. Moreover, it seems that the docker image tagged 2017-12-08 is also fine, and that custom version of protobuf is not installed.

This is the output generated if I build manually the latest image or pull the 2017-12-08 tag from Docker Hub:

```
$ docker run -it px4io/px4-dev-simulation:2017-12-08 /bin/bash
Unable to find image 'px4io/px4-dev-simulation:2017-12-08' locally
2017-12-08: Pulling from px4io/px4-dev-simulation
660c48dd555d: Already exists 
4c7380416e78: Already exists 
421e436b5f80: Already exists 
e4ce6c3651b3: Already exists 
be588e74bd34: Already exists 
2bc59ce98daa: Pull complete 
42e74bf18fff: Pull complete 
fbd23a1fa1d0: Pull complete 
9a35517cad60: Pull complete 
Digest: sha256:bcab67bc24f94e0c64495024eee0ba4f16219e75ab5d4836d1a993119ff15671
Status: Downloaded newer image for px4io/px4-dev-simulation:2017-12-08
Starting with UID : 9001
user@2b235e7500da:/$ ll /usr/local/include/
total 8
drwxr-xr-x  2 root root 4096 Nov 14 13:48 ./
drwxr-xr-x 17 root root 4096 Dec  9 02:10 ../
```

Although there are no problems building the image manually, my problem comes when I try to build px4-dev-ros, which pulls px4-dev-simulation from Docker Hub and becomes unusable.

I believe these files were added with #87. However, I can also see that the make install step was removed in commit [98400b3](https://github.com/PX4/containers/commit/98400b3ba8e55b71f7e96050628566f27242ee3c) to keep only the bloaty binary, so I am assuming they are not necessary.

Could you update the image in Docker Hub?

**Comment by dagar** [comment]
Thanks for reporting. Over the next few days I'll be taking a pass over all of these to get px4-dev-ros working properly with missing testing.
I'll be sure to cleanup things like this along the way.

**Comment by dagar** [comment]
Could you give the latest docker image a try?

**Comment by LorenzMeier** [comment]
@Butakus Could you try again?

**Comment by Butakus** [comment]
Sorry for the delay, I couldn't try before.

It seems to be fine now, so I will close the issue. Thanks for your work!
